import React from "react";
import './Menu.css';
import * as Icon from 'react-feather';


const Menu = (props) => {

  const showContent = (e) => {
    // e.preventDefault();
    const content = e.target.nextElementSibling;
    const siblings = getSiblings(e.target.parentNode);
    if (content.hidden === true) {
      content.hidden = false;
      siblings.forEach(e => e.style.display = "none")
      e.target.dataset.before = "<";
    } else {
      content.hidden = true;
      siblings.forEach(e => e.style.display = "block")
      e.target.dataset.before = "";
    }
  }

  const getSiblings = (elem) => {
    let siblings = [];
    let sibling = elem.parentNode.firstChild;
    while (sibling) {
      if (sibling.nodeType === 1 && sibling !== elem) {
        siblings.push(sibling);
      }
      sibling = sibling.nextSibling
    }
    return siblings;
  }

  return (
    <div className={props.display ? "menu show" : "menu"}>

      <div className="menu-close">
        <button className="btn" onClick={props.setToggle}><Icon.X/></button>
      </div>

      <div className="menu-item">
        <button className="menu-title" onClick={showContent} data-before="">instructions</button>
        <div className="menu-content" hidden>
          <p>instructions come here</p>
        </div>
      </div>

      <div className="menu-item">
        <button className="menu-title" onClick={showContent} data-before="">about adrift</button>
        <div className="menu-content" hidden>
          <p>
            Adrift deconstructs Google Maps direction text** and by doing so it offers a new set of directions based on the original one, thus it enables the performers to get lost in their very own environment. "Getting lost" refers to the perception of the urban fabric in a different way than what we usually experienc in <b>everyday life</b>.
          </p>
          <p>
            During the walk (or run, play, etc.) to nowhere, the performers are being asked a set of questions regarding the surrounding and offered the opportunity to record the answers in the form of conversations between them, hoping to initiate another level of observation and meaning-making through the act of walking and mapping.
          </p>
          <p>
            **<i>The mentioned Google Maps direction text (generated by the Maps directions API) is accessible by sharing the selected <b>walking directions</b> to the searched location on Maps mobile app (See the instructions).</i>
          </p>
        </div>
      </div>

      <div className="menu-item">
        <button className="menu-title" onClick={showContent} data-before="">development</button>
        <div className="menu-content" hidden>
          <p>
            Adrift is a front-end single page application (SPA) written in vanilla <b>Javascript</b>. 
          </p>
          <p>
            Adrift uses modern web API such as MediaStream Recording API and Clipboard API, which currently are <b>not supported by iOS devices</b>.
          </p>
          <p>
            The applications data storage is sessionStorage, which means after the page is reload the data will be cleaned. A frequent method for saving data (including media files) is to use cloud services, yet regarding <b>data privacy</b> issues it is prefered to use <b>client-side storage</b>. Hence, it is possible to save the drifts by saving the recordings and to do so by tapping on specifed download buttons.
          </p>
        </div>
      </div>

      <div className="menu-item">
        <button className="menu-title" onClick={showContent} data-before="">theoretical background</button>
        <div className="menu-content" hidden>
            <p>
              The "drift" and so the app are related to the concepts of "Psychogeography" and  and "Dérive".
            </p>
            <p className="quote">
              <b>Psychogeography</b> is an exploration of urban environments that emphasizes playfulness and "drifting". It has links to the Letterist and <b>Situationist International</b>s, revolutionary groups influenced by Marxist and anarchist theory, as well as by the attitudes and methods of Dadaists and Surrealists.[1] Psychogeography was defined in 1955 by Guy Debord as "the study of the precise laws and specific effects of the geographical environment, consciously organized or not, on the emotions and behavior of individuals."[2]
            </p>
            <p className="quote">
              <b>Dérive</b> (French: [de.ʁiv], "drift") is a revolutionary strategy originally put forward in the "Theory of the Dérive" (1956) by Guy Debord.[1] Debord defines the dérive as "a mode of experimental behavior linked to the conditions of urban society: a technique of rapid passage through varied ambiances."[2] It is an unplanned journey through a landscape, usually urban, in which participants drop their everyday relations and "let themselves be drawn by the attractions of the terrain and the encounters they find there". Though solo dérives are possible, Debord indicates "that the most fruitful numerical arrangement consists of several small groups of two or three people who have reached the same level of awareness, since cross-checking these different groups' impressions makes it possible to arrive at more objective conclusions."[3]
            </p>
          </div>
      </div>

      <div className="menu-item">
        <button className="menu-title" onClick={showContent} data-before="">links and references</button>
        <div className="menu-content" hidden>
          <a href="https://github.com/farzadgo/adrift" className="external" target="_blank" rel="noreferrer"> Source code repository </a>
          <a href="http://digitalmedia-bremen.de/" className="external" target="_blank" rel="noreferrer"> Digital Media Bremen </a>
          <a href="https://www.hfk2020.de/" className="external" target="_blank" rel="noreferrer"> University of the Arts Bremen </a>
          <a href="http://tbook.constantvzw.org/wp-content/derivedebord.pdf" className="external" target="_blank" rel="noreferrer"> Theory of the Dérive (PDF) </a>
          <a href="https://en.wikipedia.org/wiki/D%C3%A9rive" className="external" target="_blank" rel="noreferrer"> Dérive (Wiki) </a>
          <a href="https://en.wikipedia.org/wiki/Psychogeography" className="external" target="_blank" rel="noreferrer"> Psychogeography (Wiki) </a>
          <a href="https://www.cddc.vt.edu/sionline/" className="external" target="_blank" rel="noreferrer"> Situationist International Online </a>
          <a href="https://developer.mozilla.org/en-US/docs/Web/API" className="external" target="_blank" rel="noreferrer"> Web APIs (MDN) </a>
        </div>
      </div>

    </div>
  )
};

export default Menu;
