import React, { useState } from "react"
import './Menu.css'
import * as Icon from 'react-feather'
import { CSSTransition } from 'react-transition-group'


const Menu = ({ setToggle }) => {
  const [activeMenu, setActiveMenu] = useState('main');

  // let secondary = false;
  // const menuNodes = Array.from(document.querySelectorAll('.menu-item'));
  // menuNodes.length !== 5 ? secondary = false : secondary = true;


  const CloseMenu = ({ setToggle }) => {
    const closeBtnProps = {
      size: 36,
      strokeWidth: 1
    }
    return (
      <div className="header">
        <button className="header-btn" onClick={setToggle}>
          <Icon.X {...closeBtnProps}/>
        </button>
      </div>
    )
  }

  const MenuItem = (props) => {
    return (
      <div
        className={props.title ? "menu-item title" : "menu-item"}
        onClick={() => props.goToMenu && setActiveMenu(props.goToMenu)}>
        <span className="icon-left">{props.leftIcon}</span>
        {props.children}
        <span className="icon-right">{props.rightIcon}</span>
      </div>
    );
  }

  const RefItem = ({ leftIcon, href, children }) => {
    return (
      <h3 className="menu-item ref">
        <a href={href} target="_blank" rel="noreferrer">
          <span className="icon-left">{leftIcon}</span>
          {children}
        </a>
      </h3>
    )
  }


  return (
    <>
      {/* <div className="menu-overlay"></div> */}

      <div className="menu-container">
        <CSSTransition
          in={activeMenu === 'main'}
          timeout={500}
          classNames="menu-primary"
          unmountOnExit>
          <div className="menu">
  
            <CloseMenu setToggle={setToggle}/>
  
            <MenuItem><h3>instructions</h3></MenuItem>
  
            <MenuItem goToMenu="about" rightIcon={<Icon.ChevronRight />}>
              <h3>about Adrift</h3>
            </MenuItem>
  
            <MenuItem goToMenu="theory" rightIcon={<Icon.ChevronRight />}>
              <h3>theoretical background</h3>
            </MenuItem>
  
            <MenuItem goToMenu="dev" rightIcon={<Icon.ChevronRight />}>
              <h3>development</h3>
            </MenuItem>
  
            <MenuItem goToMenu="refs" rightIcon={<Icon.ChevronRight />}>
              <h3>links and references</h3>
            </MenuItem>
  
          </div>
        </CSSTransition>
  
        <CSSTransition
          in={activeMenu === 'about'}
          timeout={500}
          classNames="menu-secondary"
          unmountOnExit>
          <div className="menu">
            <MenuItem goToMenu="main" leftIcon={<Icon.ChevronLeft />}  title>
              <h2>adrift</h2>
            </MenuItem>
            <div className="menu-content">
              <p>
                Adrift deconstructs Google Maps direction text** and by doing so it offers a new set of directions based on the original one, thus it enables the performers to get lost in their very own environment. "Getting lost" refers to the perception of the urban fabric in a different way than what we usually experienc in <b>everyday life</b>.
              </p>
              <p>
                During the walk (or run, play, etc.) to nowhere, the performers are being asked a set of questions regarding the surrounding and offered the opportunity to record the answers in the form of conversations between them, hoping to initiate another level of observation and meaning-making through the act of walking and mapping.
              </p>
              <p>
                **<i>The mentioned Google Maps direction text (generated by the Maps directions API) is accessible by sharing the selected <b>walking directions</b> to the searched location on Maps mobile app (See the instructions).</i>
              </p>
            </div>
          </div>
        </CSSTransition>
  
        <CSSTransition
          in={activeMenu === 'theory'}
          timeout={500}
          classNames="menu-secondary"
          unmountOnExit>
          <div className="menu">
            <MenuItem goToMenu="main" leftIcon={<Icon.ChevronLeft />} title>
              <h2>theory</h2>
            </MenuItem>
            <div className="menu-content">
              <p>
                The "drift" and so the app are related to the concepts of "Psychogeography" and  and "Dérive".
              </p>
              <p className="quote">
                <b>Psychogeography</b> is an exploration of urban environments that emphasizes playfulness and "drifting". It has links to the Letterist and <b>Situationist International</b>s, revolutionary groups influenced by Marxist and anarchist theory, as well as by the attitudes and methods of Dadaists and Surrealists.[1] Psychogeography was defined in 1955 by Guy Debord as "the study of the precise laws and specific effects of the geographical environment, consciously organized or not, on the emotions and behavior of individuals."[2]
              </p>
              <p className="quote">
                <b>Dérive</b> (French: [de.ʁiv], "drift") is a revolutionary strategy originally put forward in the "Theory of the Dérive" (1956) by Guy Debord.[1] Debord defines the dérive as "a mode of experimental behavior linked to the conditions of urban society: a technique of rapid passage through varied ambiances."[2] It is an unplanned journey through a landscape, usually urban, in which participants drop their everyday relations and "let themselves be drawn by the attractions of the terrain and the encounters they find there". Though solo dérives are possible, Debord indicates "that the most fruitful numerical arrangement consists of several small groups of two or three people who have reached the same level of awareness, since cross-checking these different groups' impressions makes it possible to arrive at more objective conclusions."[3]
              </p>
            </div>
          </div>
        </CSSTransition>
  
        <CSSTransition
          in={activeMenu === 'dev'}
          timeout={500}
          classNames="menu-secondary"
          unmountOnExit>
          <div className="menu">
            <MenuItem goToMenu="main" leftIcon={<Icon.ChevronLeft />} title>
              <h2>development</h2>
            </MenuItem>
            <div className="menu-content">
              <p>
                Adrift is a front-end single page application (SPA) written in vanilla <b>Javascript</b>. 
              </p>
              <p>
                Adrift uses modern web API such as MediaStream Recording API and Clipboard API, which currently are <b>not supported by iOS devices</b>.
              </p>
              <p>
                The applications data storage is sessionStorage, which means after the page is reload the data will be cleaned. A frequent method for saving data (including media files) is to use cloud services, yet regarding <b>data privacy</b> issues it is prefered to use <b>client-side storage</b>. Hence, it is possible to save the drifts by saving the recordings and to do so by tapping on specifed download buttons.
              </p>
            </div>
          </div>
        </CSSTransition>
  
        <CSSTransition
          in={activeMenu === 'refs'}
          timeout={500}
          classNames="menu-secondary"
          unmountOnExit>
          <div className="menu">
            <MenuItem goToMenu="main" leftIcon={<Icon.ChevronLeft />} title>
              <h2>links</h2>
            </MenuItem>
            <RefItem leftIcon={<Icon.Code />} href="https://github.com/farzadgo/adrift">
              Source code repository
            </RefItem>
            <RefItem leftIcon={<Icon.ExternalLink />} href="http://digitalmedia-bremen.de/">
              Digital Media Bremen
            </RefItem>
            <RefItem leftIcon={<Icon.ExternalLink />} href="https://www.hfk2020.de/">
              University of the Arts Bremen
            </RefItem>
            <RefItem leftIcon={<Icon.File />} href="http://tbook.constantvzw.org/wp-content/derivedebord.pdf">
              Theory of the Dérive (PDF)
            </RefItem>
            <RefItem leftIcon={<Icon.BookOpen />} href="https://en.wikipedia.org/wiki/D%C3%A9rive">
              Dérive (Wiki)
            </RefItem>
            <RefItem leftIcon={<Icon.BookOpen />} href="https://en.wikipedia.org/wiki/Psychogeography">
              Psychogeography (Wiki)
            </RefItem>
            <RefItem leftIcon={<Icon.ExternalLink />} href="https://www.cddc.vt.edu/sionline/">
              Situationist International Online
            </RefItem>
            <RefItem leftIcon={<Icon.ExternalLink />} href="https://developer.mozilla.org/en-US/docs/Web/API">
              Web APIs (MDN)
            </RefItem>
            
            
          </div>
        </CSSTransition>
      </div>

    </>
  )
};

export default Menu;
